# Generated by Django 5.2.17 on 2026-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='progress_stage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='document',
            name='progress_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='progress_total_steps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
